apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  containers:
    - name: devsy
      resources:
        requests:
          cpu: 2
      volumeMounts:
        - mountPath: /workspaces/.home
          name: devsy
          subPath: devsy/home
